<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Queries\Новая папка1\**" />
    <EmbeddedResource Remove="Queries\Новая папка1\**" />
    <None Remove="Queries\Новая папка1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KDS.Primitives.FluentResult" Version="1.0.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InternshipPractice.Domain\InternshipPractice.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Queries\Новая папка2\" />
    <Folder Include="Queries\Новая папка\" />
  </ItemGroup>

</Project>
